bag_directory: "."
bag_name: "rosbag_record_mpc_2024-09-09-11-58-25.bag"
dt_ocp: 0.01
mpc_freq: 100
nb_running_nodes: 99
endeff_name: "panda_hand_tcp"

# optional parameter
mpc_data_topic_name: "/ctrl_mpc_linearized/xu_solution"
#T_sim: 2.5
mpc_solve_time_topic_name: "/ctrl_mpc_linearized/ocp_solve_time"
